Repository ACM-Amrita-Amritapuri/thats-what-C-said-about-my-PyPy, pull requests merged in 2022-10, with the labels that each got.

#1 Add files via upload
  C Programs/Cat.cs
Labels: hacktoberfest-accepted

#2 Rosalind Bioinformatics Stronghold solutions
  Python Programs/Complementing a Strand of DNA.py
  Python Programs/Compute the Hamming Distance Between Two Strings.py
  Python Programs/Compute the Number of Times a Pattern Appears in a Text.py
  Python Programs/Conditions and Loops.py
  Python Programs/Counting DNA Nucleotides.py
  Python Programs/Dictionaries.py
  Python Programs/Find All Occurences of a Pattern in a String.py
  Python Programs/Find Patterns Forming Clumps in a String.py
  Python Programs/Find a Position in the Genome Minimizing the Skew.py
  Python Programs/Find the Most Frequent Words in a String.py
  Python Programs/Find the Reverse Complement of a String.py
  Python Programs/Finding a Moif in DNA.py
  Python Programs/Implement GreedyMotifSearch.py
  Python Programs/Strings and Lists.py
  Python Programs/Transcribing DNA into RNA.py
  Python Programs/Variables and Some Arithmetic.py
  Python Programs/Working with Files.py
Labels: hacktoberfest-accepted

#15 Add files via upload
  C Programs/pull1.py
Labels: hacktoberfest-accepted

#3 Add files via upload
  Python Programs/greedy_knapsack.py
  Python Programs/roundedgrades.py
Labels: hacktoberfest-accepted

#16 Mario Easy Pattern from harvard cs50
  C Programs/mario.c
Labels: hacktoberfest-accepted

#17 Create Create Complex No Passing Structure to Function with pointer.c
  C Programs/Create Complex No Passing Structure to Function with pointer.c
Labels: good first issue, hacktoberfest-accepted

#11 pull request from ayyappa
  C Programs/Ayyappa_sam.py
Labels: hacktoberfest-accepted

#14 Add files via upload
  C Programs/Maximus_Optimus.c
  Python Programs/swordfish.md
  Python Programs/swordfish.py
Labels: good first issue, hacktoberfest-accepted

#19 Add files via upload
  Python Programs/GuessTheNumber.py
Labels: hacktoberfest-accepted

#24 Add files via upload
  Python Programs/primenumber.py
Labels: good first issue, hacktoberfest-accepted

#27 Add files via upload
  Python Programs/swapping.py
Labels: hacktoberfest-accepted

#25 Add files via upload
  Python Programs/VignereCipherAllChar.py
Labels: good first issue, hacktoberfest-accepted

#28 Add files via upload
  C Programs/pong pong.py
Labels: documentation, hacktoberfest-accepted

#29 Add files via upload
  C Programs/googleimager.py
Labels: invalid

#32 Adds python code for sorting words
  Python Programs/SortingWords.py
Labels: hacktoberfest-accepted

#36 Updated my details in Profiles.md
  PROFILES.md
Labels: documentation, good first issue, hacktoberfest-accepted

#12 Add files via upload
  Python Programs/datedetection.py
  Python Programs/inventory.py
  Python Programs/isvalidchessboard.py
  Python Programs/numberguessgame.py
Labels: good first issue, hacktoberfest-accepted

#39 01GreedyKnapsack Dynamic Programming python code
  Python Programs/01GreedyKnapsack.py
Labels: enhancement, hacktoberfest-accepted

#46 Added TaylorSeries.py
  Python Programs/TaylorSeries.py
Labels: hacktoberfest-accepted

#37 protein-protein interaction network visualizer
  Python Programs/protein-protein interaction network visualizer.py
Labels: hacktoberfest-accepted

#38 Modified contributors and profile
  CONTRIBUTORS.md
  PROFILES.md
Labels: hacktoberfest-accepted

#49 linked list.py
  Python Programs/linked list.py
Labels: hacktoberfest-accepted

#48 Added a python program
  Python Programs/roots.py
Labels: hacktoberfest-accepted

#21 Add files via upload
  C Programs/Inter_rowcol.c
  C Programs/Sorting_bubble.c
  C Programs/smallest_num.c
  C Programs/sort.c
Labels: good first issue, hacktoberfest-accepted

#41 pull_request
  C Programs/find_min_poss_num_with_k_swaps.c
  C Programs/find_num_with_given_sum.c
  C Programs/queue.c
  C Programs/repeated_subsequence.c
  C Programs/replace_binary_matrix.c
  C Programs/stack.c
Labels: good first issue, hacktoberfest-accepted

#47 solution for perfect permutation finding problem
  C++ Programs/perfect permutation.cpp
Labels: hacktoberfest-accepted

#40 Caesar from harvard cs50
  C Programs/caesar.c
Labels: hacktoberfest-accepted

#42 Create Merge_Sort.py
  Python Programs/Merge_Sort.py
Labels: hacktoberfest-accepted

#53 Added a python program
  Python Programs/treasurehunt.py
Labels: hacktoberfest-accepted

#52 Uploaded Codeforces problem solution
  Python Programs/hamburgers.py
Labels: hacktoberfest-accepted

#54 array rotation.py
  Python Programs/array rotation.py
Labels: hacktoberfest-accepted

#55 Uploaded KaratsubaMultiplication.py
  Python Programs/Karatsuba Multiplication.py
Labels: hacktoberfest-accepted

#60 added my name
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#63 Updated PROFILE.md
  PROFILES.md
Labels: hacktoberfest-accepted

#58 Cash from harvard cs50
  C Programs/cash.c
Labels: hacktoberfest-accepted

#65 Updated Contributers.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#8 Add files via upload
  C Programs/hello world.cpp
  C Programs/sample1.cpp
Labels: hacktoberfest-accepted

#33 Inverse array in python
  Python Programs/array_inversion.py
Labels: hacktoberfest-accepted

#66 Add files via upload
  Python Programs/is_substring_using regex.py
Labels: hacktoberfest-accepted

#72 Created identical_matrix.c
  C Programs/identical_matrix.c
Labels: hacktoberfest-accepted

#71 added sieve of eratosthenes in cpp
  C++ Programs/sieveOfEratosthenes.cpp
Labels: hacktoberfest-accepted

#79 Add files via upload
  Python Programs/first.py
Labels: hacktoberfest-accepted

#78 Update PROFILES.md
  PROFILES.md
Labels: good first issue, hacktoberfest-accepted

#77 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#75 Add Fibonacci Sequence python script
  CONTRIBUTORS.md
  PROFILES.md
Labels: good first issue, hacktoberfest-accepted

#59 update contributors.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#90 largest-element-with-comments-better-understanding
  C Programs/largest_element_in_array.c
Labels: hacktoberfest-accepted

#91 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#93 Create bstore.py
  Python Programs/bstore.py
Labels: hacktoberfest-accepted

#94 Create contact.py
  Python Programs/contact.py
Labels: hacktoberfest-accepted

#95 Create notemaker.py
  Python Programs/notemaker.py
Labels: hacktoberfest-accepted

#96 Create areaOfaTriangle.py
  Python Programs/areaOfaTriangle.py
Labels: hacktoberfest-accepted

#97 Added Python Programs
  Python Programs/runner.py
  Python Programs/subarray.py
Labels: good first issue, hacktoberfest-accepted

#102 Update PROFILES.md
  PROFILES.md
Labels: good first issue, hacktoberfest-accepted

#103 added a python based rock paper scissors game
  Python Programs/rockpaperscissors.py
Labels: good first issue, hacktoberfest-accepted

#104 Created a python based dice roll generator
  Python Programs/diceroll.py
Labels: hacktoberfest-accepted

#105 Suduko viswaksena
  Python Programs/suduko.py
Labels: hacktoberfest-accepted

#74 Add info to CONTRIBUTORS.md and PROFILES.md
  CONTRIBUTORS.md
  PROFILES.md
Labels: hacktoberfest-accepted

#106 Created Crank Nicolson file
  Python Programs/CrankNicolson.py
Labels: hacktoberfest-accepted

#107 Created Pascal's Triangle file
  Python Programs/PascalTriangle.py
Labels: hacktoberfest-accepted

#108 Created Gauss Elimination file
  Python Programs/GaussElimination.py
Labels: hacktoberfest-accepted

#109 Created LU Decomposition file
  Python Programs/LUDecomp.py
Labels: hacktoberfest-accepted

#110 Created Turtle Race
  Python Programs/TurtleRace.py
Labels: hacktoberfest-accepted

#111 Created Counting Valley
  Python Programs/CountingValleys.py
Labels: hacktoberfest-accepted

#112 Created Model Fit
  Python Programs/ModelFit.py
Labels: hacktoberfest-accepted

#113 Add files via upload
  Python Programs/alphabet rangoli.py
Labels: good first issue, hacktoberfest-accepted

#115 Add files via upload
  C++ Programs/Cats and a Mouse.cpp
Labels: hacktoberfest-accepted

#117 Add files via upload
  Python Programs/binarydecimal.py
Labels: hacktoberfest-accepted

#119 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#120 Update PROFILES.md
  PROFILES.md
Labels: hacktoberfest-accepted

#121 Added Solution for Walkthober problem of Round G - Kick Start 2022
  Python Programs/walkthober.py
Labels: hacktoberfest-accepted

#122 Added Solution for Largest Sum Contiguous Subarray
  Python Programs/SubarraySum.py
Labels: hacktoberfest-accepted

#123 Adds Cpp code for simple calculator
  C++ Programs/Calculator.cpp
Labels: hacktoberfest-accepted

#124 Adds googleimager.py file
  Python Programs/googleimager.py
Labels: hacktoberfest-accepted

#125 Added pong pong.py
  Python Programs/pong pong.py
Labels: hacktoberfest-accepted

#128 Add files via upload
  C++ Programs/o_str_palindrome.cpp
Labels: hacktoberfest-accepted

#130 Add files via upload
  C++ Programs/Boy or Girl.cpp
Labels: hacktoberfest-accepted

#131 Adds the python code for snakesgame.py
  Python Programs/snakes game.py
Labels: hacktoberfest-accepted

#132 Add files via upload
  Python Programs/Band name generator.py
Labels: good first issue, hacktoberfest-accepted

#133 Adds Binary to Hex Converter
  C++ Programs/AnagramChecker.cpp
  C++ Programs/BintoHex.cpp
Labels: hacktoberfest-accepted

#135 Adds Sentence Reverser
  C++ Programs/ReverseSentence.cpp
Labels: hacktoberfest-accepted

#138 Created Triangle Pattern for user defined height
  Python Programs/Triangle_Pattern.py
Labels: hacktoberfest-accepted

#146 Created a calculator using python
  Python Programs/Calculator.py
Labels: hacktoberfest-accepted

#147 Add files via upload
  Python Programs/swap case problem.py
Labels: hacktoberfest-accepted

#149 Add files via upload
  C++ Programs/Print all subarrays.cpp
Labels: hacktoberfest-accepted

#151 Floyd's Triangle
  Python Programs/Floyds triangle.py
Labels: hacktoberfest-accepted

#152 Decimal to Binary
  Python Programs/Decimal to Binary.py
Labels: hacktoberfest-accepted

#153 Armstrong
  Python Programs/Armstrong.py
Labels: hacktoberfest-accepted

#150 added contributers
  CONTRIBUTORS.md
  PROFILES.md
Labels: good first issue, hacktoberfest-accepted

#155 Add files via upload
  C Programs/Area of Triangle using coordinates.c
Labels: hacktoberfest-accepted

#156 Add files via upload
  Python Programs/PALINDROME.py
Labels: hacktoberfest-accepted

#158 Added to contributors.md and profiles.md
  C Programs/pull2.py
  C Programs/pull3.py
  C Programs/pull4.py
  C Programs/pullnew1calc.py
  CONTRIBUTORS.md
  PROFILES.md
  Python Programs/Clock_turtle.ipynb
  Python Programs/turtleClock.py
Labels: hacktoberfest-accepted

#159 Fibonacci number
  Python Programs/FibonacciNumber.py
  Python Programs/FibonacciSeries.py
  Python Programs/LogaithmCalculator.py
Labels: hacktoberfest-accepted

#163 Add files via upload
  Python Programs/ML Based Python Basics.py
  Python Programs/Python ML Questions.py
Labels: hacktoberfest-accepted

#165 Create check for leap year
  Python Programs/Find roots of quadratic equation
  Python Programs/check for leap year
Labels: invalid

#166 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: good first issue, hacktoberfest-accepted

#167 Update PROFILES.md
  PROFILES.md
Labels: hacktoberfest-accepted

#173 added-maximum-subarray-problem
  C++ Programs/maximum-sub-array.cpp
Labels: hacktoberfest-accepted

#174 Add files via upload
  Python Programs/Text wrap.py
Labels: hacktoberfest-accepted

#176 Update PROFILES.md
  PROFILES.md
Labels: hacktoberfest-accepted

#175 added cpp file for array_checker
  C++ Programs/array.cpp
  PROFILES.md
Labels: hacktoberfest-accepted

#187 Made a Pikachu drawing
  Python Programs/pattern_abstract.py
  Python Programs/pikachu.py
Labels: hacktoberfest-accepted

#186 Hello!!
  C Programs/pull1.c
  Python Programs/FibonacciNumber.py
Labels: hacktoberfest-accepted

#188 Create Doublelink.py
  Python Programs/Animalia.py
  Python Programs/Doublelink.py
Labels: hacktoberfest-accepted

#189 Create Sequence.py
  Python Programs/Sequence.py
Labels: hacktoberfest-accepted

#183 Add files via upload
  C++ Programs/Knapsack.cpp
  C++ Programs/nokiasnake.cpp
Labels: hacktoberfest-accepted

#184 added-dungeon-game.cpp
  C++ Programs/dungeon-game.cpp
Labels: hacktoberfest-accepted

#185 tokenize.py
  Python Programs/tictactoe.py
  Python Programs/tokenize.py
Labels: hacktoberfest-accepted

#191 Adds python basics
  Python Programs/PYTHON BASICS.ipynb
Labels: invalid

#195 Create list_manipulation.py
  Python Programs/list_manipulation.py
Labels: hacktoberfest-accepted

#199 Create number_guessing.py
  Python Programs/number_guessing.py
Labels: hacktoberfest-accepted

#200 Create caesar_cipher.py
  Python Programs/caesar_cipher.py
Labels: hacktoberfest-accepted

#193 Create string_sort.py
  Python Programs/string_sort
Labels: hacktoberfest-accepted

#194 Create file_handling_with_exception.py
  Python Programs/file_handling_with_exception
Labels: hacktoberfest-accepted

#212 Create PieChart.py
  Python Programs/PieChart.py
Labels: hacktoberfest-accepted

#213 Create Shutdown.py
  Python Programs/Shutdown.py
Labels: hacktoberfest-accepted

#201 Create array_sorting.cpp
  C++ Programs/array_sorting.cpp
Labels: hacktoberfest-accepted

#202 Create matrix_transpose.cpp
  C++ Programs/matrix_transpose.cpp
Labels: hacktoberfest-accepted

#203 Create matrix_sum.cpp
  C++ Programs/matrix_sum.cpp
Labels: hacktoberfest-accepted

#204 Create matrix_multiplication.cpp
  C++ Programs/matrix_multiplication.cpp
Labels: hacktoberfest-accepted

#205 added-sliding-window.cpp
  C++ Programs/sliding-window.cpp
Labels: hacktoberfest-accepted

#206 Fibonacci series upto n number
  C++ Programs/fibonacci.cpp
Labels: hacktoberfest-accepted

#207 Create arraymul.cpp
  C++ Programs/arraymul.cpp
Labels: hacktoberfest-accepted

#208 Create reverse_array
  C++ Programs/reverse_array
Labels: hacktoberfest-accepted

#209 Create factorial.cpp
  C++ Programs/factorial.cpp
Labels: hacktoberfest-accepted

#211 added python file typesoftriangle.py
  Python Programs/typeoftriangle.py
Labels: hacktoberfest-accepted

#214 RSA-algorithm-added
  C++ Programs/RSA.cpp
Labels: hacktoberfest-accepted

#219 Caesar cipher for hacktober
  C++ Programs/caesarcipher.cpp
Labels: hacktoberfest-accepted

#223 Update CONTRIBUTORS.md
  CONTRIBUTORS.md
Labels: hacktoberfest-accepted

#224 Update PROFILES.md
  PROFILES.md
Labels: hacktoberfest-accepted

#216 A game program to guess the number from 1 to 100.
  Python Programs/Number_Guessing_Game.py
Labels: hacktoberfest-accepted

#218 A calculator program to calculate numbers.
  Python Programs/Python_Calculator.py
Labels: hacktoberfest-accepted

#220 A hangman game program to guess the word.
  Python Programs/Hangman_Game.py
Labels: hacktoberfest-accepted

#222 Added python file sudokusolver.py
  Python Programs/sudokusolver.py
Labels: hacktoberfest-accepted

#225 Returns matrix in spiral form
  C++ Programs/spiral.cpp
Labels: hacktoberfest-accepted

#221 updated contributors.md
  CONTRIBUTORS.md
  PROFILES.md
Labels: good first issue, hacktoberfest-accepted

#177 transpose of a matrix.py
  Python Programs/transpose of a matrix.py
Labels: hacktoberfest-accepted

#181 upper and lowercase.py
  Python Programs/upper and lowercase.py
Labels: hacktoberfest-accepted

#180 vowels and consonants.py
  Python Programs/vowels and consonants.py
Labels: hacktoberfest-accepted

#178 pangram sentence.py
  Python Programs/pangram sentence.py
Labels: hacktoberfest-accepted

#242 Create Perceptron_And.py
  Python Programs/Perceptron_And.py
Labels: hacktoberfest-accepted

#241 Create Perceptron_Algorithm.py
  Python Programs/Perceptron_Algorithm.py
Labels: hacktoberfest-accepted

#240 Create Slytherin.py
  Python Programs/Slytherin.py
Labels: hacktoberfest-accepted

#238 Create Sieve_Of_Eratosthenes.py
  Python Programs/Sieve_Of_Eratosthenes.py
Labels: hacktoberfest-accepted

#247 Create RomanToIntiger.py
  Python Programs/RomanToIntiger.py
Labels: hacktoberfest-accepted

#246 Create atbash encrypter and decrypter
  atbash encrypter
Labels: hacktoberfest-accepted

#179 intersection of two list.py
  intersection of two list
Labels: hacktoberfest-accepted

#226 Create decay of substance graph.py
  Python Programs/decay of substance graph
Labels: hacktoberfest-accepted

#227 Create electric field of ring plot.py
  Python Programs/electric field of ring plot
Labels: hacktoberfest-accepted

#229 Create name switch basics.py
  Python Programs/name switch basics
Labels: hacktoberfest-accepted
